version: '3'

services:

  front-end:
   build:
     context: ./dont-disturbe-front-app
     dockerfile: ./Dockerfile
   image: guilhermeroque/front-end-dont-disturb
   ports:
    - "3000:3000"

  dont-disturb-service:
    build:
      context: ./dont-disturb-data-service
      dockerfile: ./Dockerfile
    image: guilhermeroque/dont-disturb-service
    ports:
     - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: users
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: guilhermeroque/dont-disturb-reverse-proxy
    ports:
     - "80:80"
    depends_on:
      - dont-disturb-service
      - front-end

  postgres:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/